// Generated by https://quicktype.io

export interface DIMJob {
    id:         string;
    name:       string;
    description: string;
    isExecuted: boolean;
    dataSet:    DataSet;
    ou:         DIMJobOu;
    pe:         PE;
    dx:         DIMJobDx;
    mapping:    Mapping;
}

export interface DataSet {
    id:   string;
    name: string;
}

export interface DIMJobDx {
    name: string;
    data: Datum[];
}

export interface Datum {
    name:       string;
    type:       string;
    id:         string;
    dimensions: any[];
}

export interface Mapping {
    ou: MappingOu;
    dx: MappingDx;
}

export interface MappingDx {
    hasMapping: boolean;
    data:       Data;
}

export interface Data {
}

export interface MappingOu {
    hasMapping:      boolean;
    mappingCriteria: MappingCriteria;
    orgUnits:        Data;
}

export interface MappingCriteria {
    code: boolean;
    id:   boolean;
}

export interface DIMJobOu {
    name:     string;
    orgUnits: OrgUnits;
}

export interface OrgUnits {
    hasUids:      boolean;
    orgUnitUids:  any[];
    orgUnitLevel: string;
}

export interface PE {
    name:       string;
    periods:    string[];
    subPeriods: any[];
}
